\
# This expression has been automatically generated by https://github.com/proger/python2nix.

{ buildPythonPackage, fetchurl, stdenv }:

buildPythonPackage rec {

  name = "graphene";

  src = fetchurl {
    url = "https://files.pythonhosted.org/packages/ad/d0/c3eb1819a9349e9ce5cb3b906a33ea59ffa2666e08a940f7551506478713/graphene-2.1.3.tar.gz";
    md5 = "e93c0b3be2503c088dddcb25350d2a59";
  };

  propagatedBuildInputs = [  ];

  meta = with stdenv.lib; {
    description = "Please read `UPGRADE-v2.0.md </UPGRADE-v2.0.md>`__ to learn how to";
    homepage = https://github.com/graphql-python/graphene;
    license = licenses.mit;
  };
}
