# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "todoist-unstable-${version}";
  version = "2018-11-09";
  rev = "4db9c55408d408ce8385ac6e845b83f320c45c28";

  goPackagePath = "github.com/sachaos/todoist";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/sachaos/todoist";
    sha256 = "1697mfq7ajr938ps387hj689k7s93274xlfyns1lr4gw1mfpxhzc";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
