#!/bin/sh
hora reg 'fillidefilla' -O csv \
  -b "$(date -d "$(date +%Y-%m)-20 last month" +%Y-%m-%d)" \
  -e "$(date -d "$(date +%Y-%m)-19" +%Y-%m-%d)" \
  | sed 's/(fillidefilla:\(.*\))/\1/g' \
  | xsv select date,amount,total,account,description
