name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [makanek,manakish,kabsa,zaatar,ful]
    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU (ARM)
      run: sudo apt-get install -y qemu-user-static
      if: ${{ matrix.system == 'ful' }}
    - name: Install Nix (ARM)
      uses: cachix/install-nix-action@v16
      if: ${{ matrix.system == 'ful' }}
      with:
        extra_nix_config: |
          system = aarch64-linux
    - name: Install Nix (x86_64)
      uses: cachix/install-nix-action@v16
      if: ${{ matrix.system != 'ful' }}
    - run: |
        rm -rf secrets
        mkdir secrets
        cat secrets.txt | while read -r path; do echo dummy > $path; done
        find
    - run: nix run nixpkgs#nixos-rebuild -- dry-build --override-input secrets ./secrets --flake .#${{matrix.system}}
