name: CI
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: [makanek,manakish,kabsa,zaatar,ful]
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
    - name: Install nixos-rebuild
      run: GC_DONT_GC=1 nix-env -i nixos-rebuild -f '<nixpkgs>'
    - run: |
        rm -rf secrets
        mkdir secrets
    - run: GC_DONT_GC=1 nixos-rebuild dry-build --flake .#{{matrix.system}}
